[package]
name = "s4-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
walkdir = "2.5.0"
rusqlite = { version = "0.31.0", features = ["bundled", "backup"] }
rust-lzma = "0.6.0"
rayon = { version = "1.10.0" }
