[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "s4a-reader"
version = "24.10.24"
requires-python = ">= 3.8"
dependencies = [
  "boto3==1.34.117",
  "lz4==4.3.3",
]